### ISSUE TITLE
Feature request: profile function for log-likelihood profiling

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2extra#1]
I think that it'd be helpful to implement a `profile()` method for fit objects to perform log-likelihood profiling.  (This is not a high priority request, and if not yet implemented, it's something that I could help with.)

**Comment by mattfidler** [comment]
Done.  Not sure what is required to move issues.

**Comment by billdenney** [comment]
@mattfidler, While working on the `profile.nlmixr2FitCore` method in the PR this morning, I realized that I was reinventing numerical optimization for about the 50th time in my career.

What I'd like to do is to use a one-dimensional minimizer trying to minimize `logLik(fit) + targetOfv` by varying each requested parameter in turn where:

1. I can give bounded optimization either between the initial model-estimated OFV and the upper bound (which may be infinite), and separately its lower bound (which also may be infinite).
2. I can inspect at each optimization step to see if any of the following conditions have been met and variously give warnings, errors, or stop the profiling process
    1. A new lower OFV has been found during the minimization
    2. The model did not converge
    3. The OFV profile is non-monotonic
3. I can obtain the trace of the estimation

Rather than reinventing all of this, I'd prefer to use parts of `nlmixr2` that are likely already available in some form.  Is there something that could do this for me in `nlmixr2`?

**Comment by mattfidler** [comment]
Not yet.  You are in luck :smile: I would suggest something like Brent's method in optim

**Comment by billdenney** [comment]
Unfortunately, Brent's method in `optim()` starts at the middle of the allowed interval, so if the limits for `lka` are c(-10, 10), and the estimate is 3, it will start the search at 0 rather than near 3.  But generally, I'm looking around there for a solution.
