### ISSUE TITLE
Unnecessary file?  nlmixr2extra.dll

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2extra#12]
I was just trying out current git versions of packages, and I noticed the "[nlmixr2extra.dll](https://github.com/nlmixr2/nlmixr2extra/blob/main/src/nlmixr2extra.dll)" file.  Should it be removed (and a .gitignore of .dll be added)?

**Comment by mattfidler** [comment]
Yep.  Needs to be removed.
