### ISSUE TITLE
Add built-in model for testing.

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2extra#18]
Add this fit to the build so that it can be tested against

```r
      one.compartment <- function() {
        ini({
          tka <- 0.45 # Log Ka
          tcl <- 1 # Log Cl
          tv <- 3.45    # Log V
          eta.ka ~ 0.6
          eta.cl ~ 0.3
          eta.v ~ 0.1
          add.sd <- 0.7
        })
        # and a model block with the error sppecification and model specification
        model({
          ka <- exp(tka + eta.ka)
          cl <- exp(tcl + eta.cl)
          v <- exp(tv + eta.v)
          d/dt(depot) = -ka * depot
          d/dt(center) = ka * depot - cl / v * center
          cp = center / v
          cp ~ add(add.sd)
        })
      }
  
 
  fit =  nlmixr2::nlmixr(one.compartment, theo_sd, est="focei")
```
you  may be interested in this issue @john-harrold

**Comment by john-harrold** [comment]
When you update nlmixr2 will this fit object be updated as well? I'm thinking about compatibility.

**Comment by mattfidler** [comment]
It should be compiled whenver nlmixr2extra is updated.

**Comment by john-harrold** [comment]
Is that part of your process. Like if you update nlmixr2 do you then resubmit nlmxir2extra to make sure it's all working together?

**Comment by mattfidler** [comment]
Typically.  But often the methods are what is updated; the fit object may have different `$` and it may not be needed to update the `nlmixr2extra`

**Comment by mattfidler** [comment]
Model will be at `nlmixr2extra::theoFitOde`
