### ISSUE TITLE
Readme.rmd example code fails to knit

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2extra#31]
I was trying to re-knit Readme.Rmd, and the code in the example chunk succeeds when run manually, but it fails when knit.

The error appears with a warning for `cli::cli_alert_danger()` because `.env$mod_idx - 1` starts with a dot.

**Comment by mattfidler** [comment]
This is new in cli 3.4. I thought I caught them all...

**Comment by billdenney** [comment]
I'm making a PR now.
