### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2extra#39]
While trying to fix the random CI failures in nlmixr2/nlmixr2#68, I found that the issue seemed to come from memory issues related to building the bootstrap documentation.  When looking at the bootstrap documentation, I noticed that there is a lot of nearly identical code in bootstrap.R and computingutil.R.  Given the fact that they are nearly the same but not the same, I'm not sure which is preferred.  @mattfidler, can you please take a look and remove one of them:

https://github.com/nlmixr2/nlmixr2extra/blob/c13dc983af7d2f5933863210df64c4a5c962852c/R/bootstrap.R#L1-L1238

https://github.com/nlmixr2/nlmixr2extra/blob/c13dc983af7d2f5933863210df64c4a5c962852c/R/computingutil.R#L296-L1527

**Comment by vsarsani** [comment]
@billdenney computingutil.R. should have all computing utilities. bootstrap.R should be redundant and probably removed sometime, but I will check.

**Comment by billdenney** [comment]
@vsarsani Thanks!
