### ISSUE TITLE
Discussion: Reconsider `extract_eq()` in favor of `knit_print(..., type = "equations")`?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2extra#52]
I was thinking about how we could be most helpful for making outputs, and since we're not really using any of the `equatiomatic` code, I thought that a `knit_print` method may be simpler for users to find and use.

The benefit is that:
* this would remove the dependency on `equatiomatic` in favor of the existing suggests for `knitr` and
* I think that `knit_print` is a more familiar method for printing things in knitr documents.

Thoughts?

**Comment by mattfidler** [comment]
I think that would be fine with me.

As a note, we don't have to import `equationmatic` we can simply register the method if it is present.

Up to you, though.

**Comment by mattfidler** [comment]
Related to #55 

Probably will need to resubmit
